### ISSUE TITLE
ANIMATION STATES: i.e. robots - work out when animations ended to then set another

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#115]

**Comment by Option4Studios** [comment]
how long is animation - wait that long in co-routine

**Comment by Rich-Option4Studios** [comment]
Still seeing yellow robot pause on a wave animation but overall it seems to rare

**Comment by Option4Studios** [comment]
Changed the delay between animation states to 2 instead of 1 like other robots.... couldn't see why would be different, should read anim time and add a second to it before animating again
