### ISSUE TITLE
GRID LAYOUTS: add to editor

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#137]
add all new background grid layouts to choose from in editor

next and back buttons with only 2 rows of 8 in editor

**Comment by Rich-Option4Studios** [comment]
https://waffle.io/option4studios/robotsgohome/cards/55be8c937bb35a0e000c8db3

**Comment by Option4Studios** [comment]
Have changed layout overlay editor to now show correct sprites, so know which grid...

Also changed, so adds number in layoutNum field when clone or create new - to stop over-writing accidentally!
