### ISSUE TITLE
LEVEL MENU: stop level overlay opening if you touch and drag while on a marker

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#142]
We have lots of level markers and it's easy to hit a level marker while scrolling through the menu. Farm Heroes doesn't open a level if you selected and dragged on a level marker

**Comment by Rich-Option4Studios** [comment]
The overlay flag was being set to true when you hit an inactive/locked level marker. I have added an extra condition to check it isn't an active marker.
