### ISSUE TITLE
Menu: 1st visit (after 1st tutorial) = hint

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#169]
overlay hints for buttons, minerals etc... dark overlay with OK button

**Comment by Laura-O4S** [comment]
![level_menu_tips](https://cloud.githubusercontent.com/assets/11822462/17084191/ee066fc6-51af-11e6-98db-ff37475f1c76.jpg)

**Comment by Rich-O4S** [comment]
![level_menu_tips](https://cloud.githubusercontent.com/assets/11824245/17085464/89e3862a-51d0-11e6-8082-850ec245fa03.jpg)
