### ISSUE TITLE
Settings: include buttons...

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#174]
- [x] delete data
- [x] iCloud restore
- [x] remove/restore ads
- [x] notifications o/off
- [x] battery saver

**Comment by Rich-O4S** [comment]
To save space, we can have the delete, saving and restoring in a seperate panel

**Comment by Rich-O4S** [comment]
I've placed in the design and hooked up the toggle buttons minus notification functionality. The text needs to be hooked up to the localisation file
