### ISSUE TITLE
NOTIFICATIONS: lives full notification (toggle on lives panel)

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#180]

**Comment by Rich-O4S** [comment]
![levelmenu_iap-alternative_0001_buy lives](https://cloud.githubusercontent.com/assets/11824245/17807037/1e846914-6600-11e6-8435-e819fc38bd46.jpg)

Note changing the + to a x3 . Can be also be x2 if we just want 1 life to be bought at a time.

**Comment by Rich-O4S** [comment]
I've setup the design in Unity
