### ISSUE TITLE
POPUP

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#198]
- [x] bought / added popups
- [x] icloud data message

**Comment by Rich-O4S** [comment]
![levelmenu_iap_0000_notification01](https://cloud.githubusercontent.com/assets/11824245/18351001/522c5350-75d0-11e6-860a-f3a7ebadfe2b.png)
![Uploading LevelMenu_IAP_0000_Notification02.png…]()
![levelmenu_iap_0000_notification03](https://cloud.githubusercontent.com/assets/11824245/18351000/5216d368-75d0-11e6-9a39-e31ef110734d.png)

Few ideas for a popup which auto dismisses

**Comment by Laura-O4S** [comment]
bought booster = show for 2 secs, then show start level overlay again...

booster bought
[name] booster added
crystals added
credits added
lives/life added

special offer = faster for every item bought

scale in/out animation + star soundFX (for now)

**Comment by Rich-O4S** [comment]
Related to [#204] - need some popups for saving and loading progress from icloud (same messages/popups as Custard).

![syn-progress-popup](https://cloud.githubusercontent.com/assets/11824245/18611060/5a736000-7d26-11e6-9d4a-29be882e5958.png)

Note - I've done some neutral tick/cross buttons as you don't want to indicate positive or negative actions.
