### ISSUE TITLE
IAP: Contacting App Store/Play Store - CHEAT to not use App Store

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#199]
Need to show correct text when on iOS or Android.

**Comment by Rich-O4S** [comment]
![levelmenu_iap_0000_contactingappstore](https://cloud.githubusercontent.com/assets/11824245/18352235/7b044dd2-75d5-11e6-9b4a-1236d1934ada.png)

**Comment by Rich-O4S** [comment]
Added this to a testUI scene

**Comment by Laura-O4S** [comment]
Moved CHEAT for using store or not, to the special/iap tab
