### ISSUE TITLE
IAP: Buy credits - new design

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#217]
New design to incorporate 2 sets of grouped prices.

I've also changed the amount of credits from textmesh pro to 2d text mesh and included the smaller 'x'. This makes them ping out over the cost

**Comment by Rich-O4S** [comment]
![levelmenu_iap_0008_buy star creditsv2a](https://cloud.githubusercontent.com/assets/11824245/18448390/e1ba42ca-7922-11e6-9929-a1bf97e9306c.png)
![levelmenu_iap_0008_buy star creditsv2a](https://cloud.githubusercontent.com/assets/11824245/18448410/f5a5dbbe-7922-11e6-9bd0-42280fd0382e.png)

**Comment by Laura-O4S** [comment]
- [ ]  change font of amounts
- [ ] show/hide panels within overlay - fade?!
- [ ] add most popular/best deal stars
