### ISSUE TITLE
BOOSTERS: Booster Crate

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#230]
I've design a booster crate sprite and added to iap spriteshet. Will add a flashing red light or two as well

**Comment by Rich-O4S** [comment]
Added the crate as a prefab. Graphic needs tweaking for the red light on top

**Comment by Laura-O4S** [comment]
Functionality in place and select animation / add booster

need to check where crate shows and which booster?!
