### ISSUE TITLE
LEVEL: moves counter

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#234]

**Comment by Rich-O4S** [comment]
![new-movespanel-01-01](https://cloud.githubusercontent.com/assets/11824245/19022693/e8e9014a-88d5-11e6-963c-4b9a29856ffb.jpg)

**Comment by Rich-O4S** [comment]
Added panel to general-ui spritesheet. Also added moves booster if we need it.
