### ISSUE TITLE
Winning Streak

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#262]
X number of winning levels in row = X

**Comment by Rich-O4S** [comment]
![artboard 1](https://cloud.githubusercontent.com/assets/11824245/22853547/10684c20-f051-11e6-8668-3427c2ef78b0.png)
![Uploading Artboard 2.png…]()

A rough idea what we can do. Could be a seperate scene and perhaps reuse the double a freegift option or something.

**Comment by Rich-O4S** [comment]
Added title texture to Textures/Winning Streak

**Comment by Rich-O4S** [comment]
Scene created along with basic script and content.csv entry
