### ISSUE TITLE
MENU IAP: Exception after buying lives. See description

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#264]
After buying lives and seeing life bought popup, got the error below and the popup didn't disappear.

ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[System.String].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
RGH.MenuScreen.ShowNextPopup () (at Assets/Scripts/TweenScripts/MenuScreen.cs:378)

**Comment by Laura-O4S** [comment]
the next popup name was missing from the array! doh! ;O)
