### ISSUE TITLE
HERO MODE: For use on astronaut level

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#288]
1. Astronaut is moved into ship and flies off
2. Hero Mode text appears
3. Bonuses are increased and change to colours below

Yellow

#faa105
250,161,5

Light Blue

0,183,236
#00b7ec

**Comment by Laura-O4S** [comment]
//show prefab
LevelScreen - ShowBonusAnim(_trans, bonusAmount, false);
