### ISSUE TITLE
END OF GAME: ?

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#289]

**Comment by Rich-O4S** [comment]
![end_of_game_mockup01.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46ed9a9e1c8d859688e8b2469b50ff97225337237846ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b884f381a0d1a8ef85834b2d4.jpg)

**Comment by Rich-O4S** [comment]
![end_of_game_mockup02.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46ed9a9e1c8d859688e8b2469b50ff97225337237b46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b884f381a0d1c88f65a31b2d4.jpg)

**Comment by Rich-O4S** [comment]
![end_of_game_mockup03.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46ed9a9e1c8d859688e8b2469b50ff97225337237a46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1e03724e28b884f381a0d1d8bfc5936b2d4.jpg)

**Comment by Rich-O4S** [comment]
Not sure if to add anything about Custard, Twitter and Facebook
