### ISSUE TITLE
ACHIEVEMENT (unlock): Design Unlock Achievement Screen

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#322]

**Comment by Rich-O4S** [comment]
![unlock_achievement01_mockup.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fd9a962c8188968eeab74aa14bf5992c483323783bae24738ef638fd0e39111d0014f9121c4d4eeefc8e29f3b23d758d0d5ee8d43f0976cf3d11a4ec824bbc08a83c990dd4e8e8d51199a26867f5819d4d3c14041d89f9583ca39c4cce5df64ef300.jpg)

**Comment by Rich-O4S** [comment]
![unlock_achievement02_mockup.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fd9a962c8188968eeab74aa14bf5992c4833237b3bae24738ef638fd0e39111d0014f9121c4d4eeefc8e29f3b23d758d0d5ee8d43f0976cf3d11a4ec824bbc08a83c990dd4e8e8d51199a26867f5819d4e3914041d89f9583ca39f4ac051f14ff300.jpg)

**Comment by Laura-O4S** [comment]
remove 'flash' at start
