### ISSUE TITLE
Failed to unlock Energize button  (see screenshot)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#333]
Didn't unlock button when all goals where met. However moved a robot and it unlocked.

**Comment by Rich-O4S** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47975d1b27de8437e545a0d18ae48585f4ca8f9dd28afa42062c80d55b98e30063e937f03a6aa8317b500bf208c4981b0bd8a4bc6ec3b37aa.JPG)

**Comment by Laura-O4S** [comment]
related to bonus score bug
