### ISSUE TITLE
Error on bonus anmiation after hitting energize (see screenshot)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#334]
LevelScreen.cs

addTimeMovesBonusSeq()...

646	textmeshPro.text = ""+tempBonus+"";

**Comment by Rich-O4S** [comment]
![Capture2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46cb958a379791acddabf301b44fff9e2c4533317346f67c2280b779ea157a045a5a1cfa43515f44f4ad897fa5bf2e6c981e5ab38532022d8c6853beb2901dbd0bbb258b4883b2ba8949c2ed3427f5c6.JPG)

**Comment by Laura-O4S** [comment]
related to bonus score bug
