### ISSUE TITLE
OVELAYS: Error purchasing appearing on successful mineral purchase (see desc)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#435]
1. Purchase Credits
2. Hit Cancel on iOS 'Purchase credits' popup
3. An error purchasing etc overly appears
4. Buy minerals e.g 5
5. Success buying minerals overlay appears
6. Close overlay
7. An error purchasing etc overly appears

**Comment by Laura-O4S** [comment]
i think i've fixed this, but need to test on device
