### ISSUE TITLE
Brackets: Improve graphic + positions

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#449]

**Comment by Rich-O4S** [comment]
![Untitled-1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46dd9a8e2a968fac8ba4ee01e81fe086264c22703d46f96925d2b12deb132e560e0a4ba9130e5d4dfcf9817fa6e23f79984019af80330b2b9b645bf9fa9015ad00bd2a8a4a84bfbc8c4ac7e83e24ee829d02.jpg)

**Comment by Laura-O4S** [comment]
- [x] tutorial full brackets 
- [ ] booster brackets (4)
