### ISSUE TITLE
QT: converter/teleporter - set layouts - guide which to 'change/swap' -- storyboard

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#451]

**Comment by Rich-O4S** [comment]
Teleporter

![tutorial4a_teleporter.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bdbe7cb058fc91394935672c16e1673295f127b54778154d555ca9465a0a40fdfc8e7af3b33922dc5e02edd1650b74923e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e463e1b041080fc5f36a48b06.png)
![tutorial4b_teleporter.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bdbd7cb058fc91394935672c16e1673295f127b54778154d555ca9465a0a40fdfc8e7af3b33922dc5e02edd1650b74923e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e463e1b041080fc5f37a88b06.png)
![tutorial4c_teleporter.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bdbc7cb058fc91394935672c16e1673295f127b54778154d555ca9465a0a40fdfc8e7af3b33922dc5e02edd1650b74923e18bea4905dee5fee7fd616cfe3fe9846d2e9342fe68e8e463e1b041080fc5f3ca48b06.png)
![tutorial4d_teleporter.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bdbb7cb058fc91394935672c16e1673295f127b54778154d555ca9465a0a40fdfc8e7af3b33922dc5e02edd1650b74923e18bea4905dee5fee7fd616cfe3fe9846d2e93a2fe68e8e463e1b041080fc5f30a18b06.png)

**Comment by Rich-O4S** [comment]
Convertor

I've experimented with using full colour tiles for the convertor panel, with slighly larger sprites (5-10% larger)

![tutorial5a_convertor.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bcbe7ca752fe822c54337c3b46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a864f3b1f0c1a8afb5433b2d4.png)
![tutorial5b_convertor.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bcbd7ca752fe822c54337c3b46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a864f3b1f0c1a8afa5f32b2d4.png)
![tutorial5c_convertor.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bcbc7ca752fe822c54337c3b46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1e13724e28a864f3b1f0c1a8afb5430b2d4.png)
![tutorial5d_convertor.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46fc818e2c908aa883bcbb7ca752fe822c54337c3b46ef696097ec22ba416f43554d4bab430d5b45f9fed87ea3b36e2688550bedd9395f20c53403b0aac04ee155e57dd205d0f4ae805ec1ef3724e28a864f3b1f0c1a8afb5430b2d4.png)
