### ISSUE TITLE
Buying booster in Menu/Level - need some sort of visual/audio feedback on successful purchase

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#473]

**Comment by Laura-O4S** [comment]
Check all have AddBuy/Toast

**Comment by Laura-O4S** [comment]
LEVEL:
1. soundFX when bought booster - kerchinnggg
2. buy overlay > toast > useBooster overlay

MENU:
Toast over top of start overlay - stop any buttons while showing?

Remove AddBuy in menu, if buy in level!

**Comment by Laura-O4S** [comment]
Have placed toast, whenever buy booster
if in level, = 2. above - hides booster overlay > toast > shows useBoooster overlay
