### ISSUE TITLE
MENU: Buy Booster > Buy Crystals > Can hear but can't see Toast

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#487]

**Comment by Rich-O4S** [comment]
The Toast can be only been seen by the Menu UI Camera. The IAP UI Camera however is enabled at this point and takes precedence over the Menu UI Camera.

However it can be argued that we don't need the Crystals Toast as we have the ' Crystals Added' overlay on.

**Comment by Laura-O4S** [comment]
this might be the overlays issue, sitting on top of toast...?
