### ISSUE TITLE
MAD ROBOT: tween script null exception - QT or all levels?

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#513]

**Comment by Rich-O4S** [comment]
@Laura-O4S Sorry I thought this was just an animation thing, but actually it's related to  moving the robot on the grid.

NullReferenceException: Object reference not set to an instance of an object
robots.CheckRobots.FindMove (System.String _tile, Boolean _top, Boolean _right, Boolean _bottom, Boolean _left, Int32 _madRobotNum) (at Assets/Scripts/Game/CheckRobots.cs:787)
RGH.MadRobotTweens.SetNextMove () (at Assets/Scripts/RobotTweenScripts/MadRobotTweens.cs:108)
RGH.MadRobotTweens+<MadRobotCoroutine>c__Iterator0.MoveNext () (at Assets/Scripts/RobotTweenScripts/MadRobotTweens.cs:78)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
