### ISSUE TITLE
OUT OF MOVES: Booster button icon change (see desc)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#519]
I had one move left..I decided to buy a  converter which it then showed the 'Out of moves' panel. I bought the moves, used them and it returned to normal gameplay. The Converter booster button seems to have changed into a moves booster icon?

Note, it still functions as a converter button despite the icon...however the converter wasn't working properly, couldn't then select a robot (the debug log was outputting the robot name I was tapping though).

**Comment by Rich-O4S** [comment]
![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47975d1b27de8437e545a0d18ae48585f4ca8f9dd28afa42062c80d55b98e30063e937f03a6aa8317b500bf228a4b8cb1b98d4cc3eb3537aa.JPG)

**Comment by Laura-O4S** [comment]
This overlay is now only showing when failed 3 levels in a row, and have 1 move left... check whether this makes sense, if just about to gain goals.... and that this error (above) doesn't happen...
