### ISSUE TITLE
OUT OF MOVES: Showing at wrong time (see desc)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#520]
Was testing the teleporter (used that 5 times in a row. Had 10 moves left but the Out Of Moves panel came up.

**Comment by Laura-O4S** [comment]
see 519

I'm not sure whether this will show when it should at the moment, as we no longer use the boughtCurrency IAPState (i think!)

Need to relook at when and how this panel shows...

**Comment by Laura-O4S** [comment]
Removed from here - now only shows if have failed 3 levels in a row, then have 1 move left. see 519 for testing this makes sense
