### ISSUE TITLE
OVERLAYS: Buying booster by buying two lots of crystals

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#525]
1. Start with no or little crystals
2. Buy a converter/teleporter booster > Buy more Crystals (500)
3. Try to bu booster again > You don't have enough crystals still, buy another 500
4. Panel doesn't return, background image on

**Comment by Laura-O4S** [comment]
i've stopped the 'remove' of the last overlay in the previousOverlay list - so when open another overlay again, knows where to go back to..... need to test with credit, minerals - menu and level!
