### ISSUE TITLE
NullExpection: Crate

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#556]
NullReferenceException: Object reference not set to an instance of an object
RGH.IAPUIManager.ShowToast (IAPType _toast) (at Assets/Scripts/Managers/IAPUIManager.cs:1627)
RGH.CrateTweens.Selected () (at Assets/Scripts/RobotTweenScripts/CrateTweens.cs:98)
RGH.CrateTweens.OnMouseDown () (at Assets/Scripts/RobotTweenScripts/CrateTweens.cs:17)
UnityEngine.SendMouseEvents:DoSendMouseEvents(Int32)

**Comment by Laura-O4S** [comment]
leave as is
