### ISSUE TITLE
IAP: Not sure updating of iap prices is used

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#559]
GameStateManager.tierInfo is updated but there doesn't seem to be any evidence is used to look up prices.

For testing purposes, I've changed local price of 0.99 to 0.96 so we know.

**Comment by Rich-O4S** [comment]
Also, the local tiers are UK centric. Do we need US, GB, AUS, NZ locals tiers even though 99.99% of the time it will revert to the stored app prices in GameStateManager.tierInfo?

**Comment by Rich-O4S** [comment]
Although the credits prices haven't updated on the iPad, it seems like the Remove Adverts price has been updated to £1.99

**Comment by Laura-O4S** [comment]
Set correct order!
