### ISSUE TITLE
Currency Sign

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#560]
I think when updating prices from the App store, it may include the currency sign as well.

So maybe we can show the sign but only if it's TextMeshPro as this can suppport a few currency signs of:

pounds
dollars
euro
yen / China Yuan Renminbi  (¥)
cents (¢) - wouldn't be required?

2DTextMesh font only supports the dollar and pounds signs unless I make the effort of adding them...which I can't remember how to do :)

**Comment by Laura-O4S** [comment]
€, ¥, £, $
