### ISSUE TITLE
Notifications: when select no = yes on settings - can do anything about?

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#570]

**Comment by Rich-O4S** [comment]
Found possible methods for iOS to check user permissions and implemented (was on a different page in the help guide weirdly). Need to test.

Android, there should be a way to check but Stan hasn't implemented it.

**Comment by Rich-O4S** [comment]
iOS now detectes if the device notif setting is off, however we need a message to say when we try to turn it on in the settings that the user needs to change it in the settings as well
