### ISSUE TITLE
GDPR: check we're compliant!

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#592]
Should we have a consent panel on first play?

**Comment by Laura-O4S** [comment]
opt out of analytics?

**Comment by Rich-O4S** [comment]
https://support.vungle.com/hc/en-us/articles/360003455452-Get-Started-with-Vungle-SDK-v-6-Unity

**Comment by Rich-O4S** [comment]
https://unity3d.com/legal/gdpr

**Comment by Rich-O4S** [comment]
https://unityads.unity3d.com/help/legal/gdpr
