### ISSUE TITLE
Level 57 - Bad Robot (see desc)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#603]
Part 1
-------

When Bad Robot showed, at least 2 matched robots initiated their 'connected' VFX and SFX

Part 2
--------
When Bad Robot moved, the Blue battery VFX would activate. At this point 2 blue robots were connected and 2 green robots were also connected, both targets reached. The yellow target was not reached and now yellow were connected

Part 3
-------
I knew I had failed the level, so used up all my moves. This initiated the end of level sequence up to showing the score. The Failed banner didn't show and I was stuck. Unable to exit and had to close the game.

**Comment by Rich-O4S** [comment]
Repeated Warningd

DOTWEEN :: An error inside a tween callback was silently taken care of > Object reference not set to an instance of an object

  at RGH.EffectsManager.BatteryFullEffect (Int32 _batteryNum) [0x00217] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\Managers\EffectsManager.cs:225 
  at RGH.LevelScript.UpdateTotals (Boolean _endLevel) [0x0029e] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\LevelScript.cs:762 
  at robots.CheckRobots.ColourTiles () [0x0044f] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\Game\CheckRobots.cs:466 
  at robots.Tweens.EndTileSwitch (Boolean _allow, UnityEngine.Transform _trans, Int32 _zdepth) [0x0005b] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\Game\Tweens.cs:97 
  at robots.Tweens+<setRobotSwitch>c__AnonStorey0.<>m__0 () [0x0000e] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\Game\Tweens.cs:61 
  at DG.Tweening.Tween.OnTweenCallback (DG.Tweening.TweenCallback callback) [0x00007] in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween\Tween.cs:276 


UnityEngine.Debug:LogWarning(Object)
DG.Tweening.Core.Debugger:LogWarning(Object) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/Debugger.cs:26)
DG.Tweening.Tween:OnTweenCallback(TweenCallback) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:278)
DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:260)
DG.Tweening.Core.TweenManager:Goto(Tween, Single, Boolean, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:645)
DG.Tweening.Sequence:ApplyInternalCycle(Sequence, Single, Single, UpdateMode, Boolean, Boolean, Boolean) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:310)
DG.Tweening.Sequence:DoApplyTween(Sequence, Single, Int32, Int32, Boolean, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:216)
DG.Tweening.Sequence:ApplyTween(Single, Int32, Int32, Boolean, UpdateMode, UpdateNotice) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Sequence.cs:143)
DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:247)
DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:436)
DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)

**Comment by Rich-O4S** [comment]
Last warning when banner didn't appear

DOTWEEN :: An error inside a tween callback was silently taken care of > Object reference not set to an instance of an object

  at RGH.EffectsManager.BatteryFullEffect (Int32 _batteryNum) [0x00217] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\Managers\EffectsManager.cs:225 
  at RGH.LevelScript.UpdateTotals (Boolean _endLevel) [0x0029e] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\LevelScript.cs:762 
  at robots.LevelScreen.LevelEnd () [0x0002a] in F:\Unity\VersionControl\robotsgohome\Assets\Scripts\TweenScripts\LevelScreen.cs:891 
  at DG.Tweening.Tween.OnTweenCallback (DG.Tweening.TweenCallback callback) [0x00007] in D:\DG\_Develop\__UNITY3_CLASSES\_Holoville\__DOTween\_DOTween.Assembly\DOTween\Tween.cs:276 


UnityEngine.Debug:LogWarning(Object)
DG.Tweening.Core.Debugger:LogWarning(Object) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/Debugger.cs:26)
DG.Tweening.Tween:OnTweenCallback(TweenCallback) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:278)
DG.Tweening.Tween:DoGoto(Tween, Single, Int32, UpdateMode) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Tween.cs:260)
DG.Tweening.Core.TweenManager:Update(UpdateType, Single, Single) (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/TweenManager.cs:436)
DG.Tweening.Core.DOTweenComponent:Update() (at D:/DG/_Develop/__UNITY3_CLASSES/_Holoville/__DOTween/_DOTween.Assembly/DOTween/Core/DOTweenComponent.cs:51)

**Comment by Rich-O4S** [comment]
Video

https://www.dropbox.com/s/3sy1lfu05mn3hjr/Issue603_BadRobot.mp4?dl=0

**Comment by Rich-O4S** [comment]
As far as I can see, the condition is never met during normal play, the childCount==0. Hwoever when it goes wrong with the yellow warnings, childCount==1 and that condition is met:



	if (childGO.transform.childCount > 0 && _batteryNum < 4)
			{
				Debug.Log("EffectsManager > Condition true > rVFX: " + _batteryNum);

				GameObject VFXPrev = GameObject.Find("rVFX" + _batteryNum + "").gameObject; 
				VFXPrev.transform.Find("Bubble").gameObject.SetActive(true);
				PlayEffects("GroupRobot", VFXPrev);
			}
			else
			{
				SetUpEffects("GroupRobot", groupVFX, "rVFX" + _batteryNum + "", 0f, 0f, -2f, childGO, true, true);
				GameObject VFX1 = GameObject.Find("rVFX" + _batteryNum + "").gameObject;
				PlayEffects("GroupRobot", VFX1);
				//Invoke("DestroyGoalVFX", 1);
				this.Invoke(DestroyGoalVFX, 1F);
			}

**Comment by Laura-O4S** [comment]
Fixed by adding try/catch around play FX

this seems to have fixed, but if happens again, try:
adding a new var to the mad robot coroutine (wait fixed update), this var is set when it's 'our turn' i.e. the switch is taking place - then unset on EndTileSwitch
