### ISSUE TITLE
Level 138, 212,224: Doesn't start and crashes game - remove comets

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#617]

**Comment by Laura-O4S** [comment]
is it timing of 'rebuilding grid' vs comet/special character min time?

**Comment by Rich-O4S** [comment]
I can recreat it on my PC with the Profiler on and Deep Profiling enabled. This is the last screenshot when it freezes. With more debug logs we could narrow it down.

![Capture.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47975d1b27de8437e545a0d18ae48585f4ca8f9dd28afa42062c80d55b98e30063e937f03a6aa8317b500bf228c4d83bfbe894dc1ed3c37aa.JPG)

**Comment by Laura-O4S** [comment]
team decision - remove comets! - due to also being able to swap robots while comet in progress
