### ISSUE TITLE
In-App Purchasing/Restore, contacting App Store remains (See desc - updated)

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#627]
1. Settings
2. Restore Purchase
3. Cancel Sign in
4. Failed panel appears & disappears
4. Contacting App Store remains on screen

Debug Log

RestorePurcahses started
RestorePurchases continuing: False. If no further messages, no purchases available to restore

**Comment by Rich-O4S** [comment]
![IMG_1295.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46c1b9bd1cd3d1f0daabf301b44fff9e2c4533317346f67c2280b779ea157a045a5a1cfa43515f44f4ad897fa5bf2e6c981e5ab38532022d8c6853beb2901eb80bbb25894784bfbf894cc6e13b22f5c6.PNG)

![IMG_1296.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46c1b9bd1cd3d1f0d9abf301b44fff9e2c4533317346f67c2280b779ea157a045a5a1cfa43515f44f4ad897fa5bf2e6c981e5ab38532022d8c6853beb2901eb70bbb25894784bfbf894dc7ec3d2cf5c6.PNG)

**Comment by Laura-O4S** [comment]
Special Offer Scene: Contacting App Store doesn't disappear if cancel purchase

**Comment by Laura-O4S** [comment]
Adverts Scene: Contacting App Store doesn't disappear if cancel purchase

**Comment by Rich-O4S** [comment]
Special Offer Scene: Contacting App Store doesn't disappear &  Purchase failed, however purchase was successful
