### ISSUE TITLE
TUTORIAL: Goes funky doing steps too early

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#67]

**Comment by Rich-Option4Studios** [comment]
there's brief windows when you can move none tutorial robots. This then makes it impossible to move tutorial robots and complete level

**Comment by Option4Studios** [comment]
think this is fixed, although need to double check arrow at end - i think it sometimes sticks...

**Comment by Option4Studios** [comment]
Still an issue with "there's brief windows when you can move none tutorial robots. This then makes it impossible to move tutorial robots and complete level"

Move the blue and green robot top corner first as an example

**Comment by Rich-Option4Studios** [comment]
The initial problem might be solved however if you swap the blue and green robot really quickly they get stuck on each other. This doesn't occur on other levels so I think its tutorial related.
