### ISSUE TITLE
Check level 8/Crate

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#672]
See if it freezes

**Comment by Rich-O4S** [comment]
I could replicate it by quickly tapping the crate at the same time of moving a couple of robots.

To quickly test, replace save file with below which is set at level 8.

https://www.dropbox.com/s/gmjhpbreqip688p/rghsaves.dat?dl=0

**Comment by Laura-O4S** [comment]
crate not being destroyed on select
