### ISSUE TITLE
NOTIFICATIONS

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#69]
Do we need the standard iOS nofication:

"Robots Go Home! Would Like to Send You Notifications.

Notifications may include alerts, sounds and icon badges. etc"

What notification would we have?

**Comment by Laura-O4S** [comment]
also for lives!

**Comment by Rich-O4S** [comment]
If lives are full, then do a normal notification of 'Come back to RGH etc'.  However lets have 4-5 variations, maybe even mention 'You're lives are full. Give level X a try'

**Comment by Rich-O4S** [comment]
If we want a universal notification plugin, which can schedule and also have repeated notifications

https://www.assetstore.unity3d.com/en/#!/content/37767

**Comment by Rich-O4S** [comment]
Notication dates added to Google Sheets. Might be nice to have custom badges as wel, e.g christmas tree for christmas day
