### ISSUE TITLE
LEVEL: booster buttons can stay stuck on a slightly larger size.

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#70]
![image](https://cloud.githubusercontent.com/assets/11824245/7459022/e955bb32-f290-11e4-868b-f597ed4f76f1.jpg)
![image](https://cloud.githubusercontent.com/assets/11824245/7459023/e959bdf4-f290-11e4-8843-9ce9f92187d1.jpg)

**Comment by Laura-O4S** [comment]
remove scale on mousedown - all booster buttons
