### ISSUE TITLE
DAILY GIFT: Reveal Cards

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#741]
1. Selected first card (I think)
2. Revealed 500 Crystals
3. Hit Double this (had enough credits)
4. Made success noise but nothing happened. Card stayed there, tapping double this and ok again did nothing. Stuck in scene. No errors logged.

Reopened game, had no credits and didn't add crystals either

**Comment by Laura-O4S** [comment]
reconnected missing scripts in triggered animation
