### ISSUE TITLE
How is energized robots tally stored - like the scores?

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#745]
Just wondering. I've set Game Center to have the latest overall score rather than top score. So if someone does a  level again and gets a lower score, the overall score should be lower too.

**Comment by Laura-O4S** [comment]
stars, scores and robots energised, are all set as highest scored for each level i.e. if have 6 energised robots and okay level and get 10 energised robots, the levels 'value' will be increased to 10 (but won't ever save lower)
