### ISSUE TITLE
Incorrect Robot blown up Level 191

### ISSUE THREAD

**Issue by Rich-O4S** [Laura-O4S/PROJECTVOYAGEHOME#756]
Space mine near the head, blew up robot in the bottom left hand!

**Comment by Rich-O4S** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/572e3f4b90b2fd1300eb411b/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47975d1b27de8437e545a0d18ae48585f4ca8f9dd28afa42062c80d55b98e30063e937f03a6aa8316b500bf238e4887bebf824bc5ee3437aa.PNG)

**Comment by Laura-O4S** [comment]
cannot replicate - see level 241 (jump from cheat)
