### ISSUE TITLE
DAILY GIFTS: design screen

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#94]
* Wheel with 5-6 segments
* Segments will have boosters. Minerals should be the 'lowest odds'.
* Chief as glamorous assistant
* Laser beam/particle effect for the clicker thing
* Daily spin accessed from button on menu (Maybe come up automatically first time).
* Success/prize overlay

**Comment by Rich-Option4Studios** [comment]
I've created a gift-achievement spritesheet which contains the cards and the static robots. I've added a longer buy button in the iap spritesheet.
