### ISSUE TITLE
OVERLAYS: IAP Sale = set file to store 'sale' info and read it in to show on iap panels

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#96]

**Comment by Option4Studios** [comment]
think about pricing and tiers - how it fits with Soomla and Apple

**Comment by Option4Studios** [comment]
- [ ] add elastic animation on stars

**Comment by Option4Studios** [comment]
almost there - need to show when give more minerals for number of credits?

**Comment by Laura-O4S** [comment]
change to say which are on offer = reads iap tier - 1 [#181]
