### ISSUE TITLE
ASTRONAUT/PUZZLE: animation when get astronaut home - show adding credits within animation

### ISSUE THREAD

**Issue by Laura-O4S** [Laura-O4S/PROJECTVOYAGEHOME#97]

**Comment by Option4Studios** [comment]
decide how this is going to work?
snapshot of points/matches and then at end  = difference = bonus?

is astronaut going to disappear into 'ship'/satellite and be replaced by new robot?

do we need a bigger 'tile' - to show a ship/satellite = layout grid change... also use an 'X' like current and need to get him here...

**Comment by Option4Studios** [comment]
1. Pause time
2. Astronaut sucked into ship airlock
3. Empty tile is filled by a robot
4. Ship swaps sprite to closed  airlock
5. Engine flame get bigger/stronger
6. Lots of points go from ship to score
7. Energy explosions from matched robots?
8. Big '+5 Star Credits'
9. Ship flies off
10. Timer resumes
